version: "3.8"

networks: 
  net_inception: 
    driver: bridge

volumes:
  v_mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yugao/data/mariadb
  v_wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/yugao/data/wordpress

services:
  nginx:
    container_name: nginx
    build:          ./requirements/nginx
    depends_on:     
      - wordpress
    ports:
      - 443:443
    volumes:
      - v_wordpress:/var/www/html
    networks:
      - net_inception
    restart:  always
  wordpress:
    container_name: wordpress
    build:          ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - v_wordpress:/var/www/html
    networks:
      - net_inception
    env_file:
      - .env
    restart:  always
  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - v_mariadb:/var/lib/mysql
    networks:
      - net_inception
    env_file:
      - .env
    restart:  always

    

