version: "3.8"

networks: 
  yugao: 

volumes:
  wordpress:
  mariadb:

services:
  nginx:
    container_name: nginx
    build:          ./requirements/nginx
    depends_on:     
      - wordpress
    ports:
      - "443:443"
    volumes:
      - type: volume
        source: wordpress
        target:  /var/www/html
    networks:
      - yugao
    env_file:
      - .env
    restart:  always
  wordpress:
    container_name: wordpress
    build:          ./requirements/wordpress
    depends_on:
      - mariadb
    volumes:
      - type: volume
        source: wordpress
        target:  /var/www/html
    networks:
      - yugao
    env_file:
      - .env
    restart:  always
  mariadb:
    container_name: mariadb
    build:          ./requirements/mariadb
    volumes:
      - type: volume
        source: mariadb
        target:  /var/lib/mysql
    networks:
      - yugao
    env_file:
      - .env
    restart:  always

    

